from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pydbml import Database
from pydbml.classes import Column, Enum, EnumItem, Note, Reference, Table

from . import properties, relations
from .aldoc import AldocDocs
from .grouping import GroupingConfig, build_table_groups
from .symbols import load_symbols
from .types import map_al_type


@dataclass
class _PendingRef:
    source_table: str
    source_field: str
    target_table: str
    target_field: str | None
    condition: str | None  # the AL WHERE(...) filter, when present
    if_condition: str | None = None  # the IF (...) clause for conditional refs


@dataclass
class Generator:
    """Build a ``pydbml.Database`` from a parsed AL ``SymbolReference.json`` document.

    The pipeline:

    1. Build enums (skipping empty ones — DBML requires at least one item).
    2. Apply enum extensions on top.
    3. Build tables with PK flags and column notes, collecting deferred references.
    4. Either merge ``TableExtensions`` into their target tables or emit them as separate
       stub tables, depending on ``merge_extensions``.
    5. Resolve references with graceful fallbacks for cross-package or missing-field cases.
    6. Build ``TableGroup``s according to ``GroupingConfig``.
    """

    symbols: dict[str, Any]
    merge_extensions: bool = True
    grouping: GroupingConfig = field(default_factory=GroupingConfig)
    table_schema: str = "dbo"
    enum_schema: str = "meta"
    includes: list[str] = field(default_factory=list)
    excludes: list[str] = field(default_factory=list)
    docs: AldocDocs = field(default_factory=AldocDocs)
    db: Database = field(default_factory=Database)

    _enums: dict[str, Enum] = field(init=False, default_factory=dict)
    _tables: dict[str, Table] = field(init=False, default_factory=dict)
    _columns: dict[tuple[str, str], Column] = field(init=False, default_factory=dict)
    _pending_refs: list[_PendingRef] = field(init=False, default_factory=list)
    _table_namespaces: dict[str, str] = field(init=False, default_factory=dict)
    _built: bool = field(init=False, default=False)

    @classmethod
    def from_app(cls, path: str | Path, **kwargs: Any) -> Generator:
        """Construct a :class:`Generator` directly from a compiled AL ``.app`` package."""
        return cls(symbols=load_symbols(path), **kwargs)

    def build(self) -> Database:
        """Run the full pipeline and return the populated :class:`pydbml.Database`."""
        if self._built:
            return self.db
        self._build_enums()
        self._extend_enums()
        self._build_tables()
        if self.merge_extensions:
            self._merge_table_extensions()
        else:
            self._build_extension_stubs()
        if self.includes or self.excludes:
            self._apply_table_filters()
        self._resolve_references()
        self._build_groups()
        self._built = True
        return self.db

    def dbml(self) -> str:
        """Build (if needed) and render the database as a DBML string with a header comment."""
        body = self.build().dbml
        return self._header_comment() + body

    def _header_comment(self) -> str:
        """Return a short provenance preamble identifying the tool + source package."""
        from . import __version__

        name = self.symbols.get("Name")
        version = self.symbols.get("Version")
        publisher = self.symbols.get("Publisher")
        app_id = self.symbols.get("AppId")

        descriptor_parts: list[str] = []
        if name:
            descriptor_parts.append(str(name))
        if version:
            descriptor_parts.append(str(version))
        descriptor = " ".join(descriptor_parts)
        publisher_suffix = f" by {publisher}" if publisher else ""

        if descriptor:
            first = f"// Generated by al2dbml {__version__} from {descriptor}{publisher_suffix}\n"
        else:
            first = f"// Generated by al2dbml {__version__}\n"

        second = f"// AppId: {app_id}\n" if app_id else ""
        return first + second + ("\n" if first or second else "")

    def stats(self) -> dict[str, int]:
        """Return a snapshot of how many of each object kind the build produced.

        Useful as a quick sanity check on any ``.app``: an extension with only
        codeunits produces ``{'tables': 0, ...}`` and explains an empty diagram.
        """
        self.build()
        return {
            "tables": len(self._tables),
            "columns": len(self._columns),
            "enums": len(self._enums),
            "refs": len(self.db.refs),
            "groups": len(self.db.table_groups),
        }

    @staticmethod
    def _enum_item_name(raw: Any) -> str | None:
        """Coerce an AL enum value name into something DBML can render.

        AL's ``Enum`` literals are often named with a literal space (``" "``) to
        represent the default/blank slot, which DBML accepts as a quoted item. An
        empty string (``""``) however breaks DBML's parser; substitute a single
        space so the value still appears in the diagram in its expected position.
        """
        if raw is None:
            return None
        text = str(raw)
        if text == "":
            return " "
        return text

    @staticmethod
    def _enum_item(value_def: dict[str, Any]) -> EnumItem | None:
        """Build a pydbml ``EnumItem`` from one AL enum value definition.

        Returns ``None`` when the value has no usable ``Name``. AL omits the
        ``Ordinal`` key when the value is at position 0, so missing -> 0.
        The ordinal is attached as a DBML note (``[note: '<n>']``) so the
        integer-to-name mapping that BC stores in SQL is visible in the diagram.
        """
        item_name = Generator._enum_item_name(value_def.get("Name"))
        if item_name is None:
            return None
        ordinal = value_def.get("Ordinal", 0)
        return EnumItem(name=item_name, note=str(ordinal))

    def _build_enums(self) -> None:
        for entry in self.symbols.get("EnumTypes") or []:
            name = entry.get("Name")
            if not name:
                continue
            items_raw = entry.get("Values") or entry.get("Items") or []
            items: list[EnumItem] = []
            for v in items_raw:
                if not isinstance(v, dict):
                    continue
                item = self._enum_item(v)
                if item is not None:
                    items.append(item)
            if not items:
                continue
            # Enums get their own schema (default 'meta') rather than sharing
            # the table schema. BC enums are AL-language metadata that doesn't
            # actually exist in SQL Server, so a separate namespace tells the
            # reader 'this is descriptor, not data' while still being a real
            # DBML object the column types can reference unambiguously.
            enum_obj = Enum(name=name, schema=self.enum_schema, items=items)
            self._enums[name] = enum_obj
            self.db.add(enum_obj)

    def _extend_enums(self) -> None:
        for ext in self.symbols.get("EnumExtensionTypes") or []:
            target = ext.get("TargetObject") or ext.get("Target")
            enum_obj = self._enums.get(target) if target else None
            if enum_obj is None:
                continue
            for v in ext.get("Values") or ext.get("Items") or []:
                if not isinstance(v, dict):
                    continue
                item = self._enum_item(v)
                if item is not None:
                    enum_obj.items.append(item)

    def _build_tables(self) -> None:
        for table_def in self.symbols.get("Tables") or []:
            name = table_def.get("Name")
            if not name:
                continue
            table = self._make_table(table_def)
            self._tables[name] = table
            self._table_namespaces[name] = str(table_def.get("__namespace") or "")
            self.db.add(table)

    def _make_table(self, table_def: dict[str, Any]) -> Table:
        name = table_def["Name"]
        props = properties.normalize(table_def.get("Properties"))
        caption = props.get("Caption")
        # aldoc summary (sourced from AL /// <summary> doc comments) is
        # strictly richer prose than the bare Caption; prefer it when present.
        table_note = self.docs.table_summaries.get(name) or caption
        table = (
            Table(name=name, schema=self.table_schema, note=table_note)
            if table_note
            else Table(name=name, schema=self.table_schema)
        )

        keys = table_def.get("Keys") or []
        pk_names: set[str] = set()
        if keys and isinstance(keys, list):
            first_key = keys[0]
            if isinstance(first_key, dict):
                pk_names = set(first_key.get("FieldNames") or [])

        for f in table_def.get("Fields") or []:
            col = self._make_column(name, f, pk_names)
            if col is not None:
                table.add_column(col)
                self._columns[(name, col.name)] = col

        # Single-field secondary keys imply uniqueness; multi-field keys are
        # deliberately deferred to a future "secondary keys as indexes" slice.
        for key in keys[1:] if isinstance(keys, list) else []:
            if not isinstance(key, dict):
                continue
            field_names = key.get("FieldNames") or []
            if len(field_names) != 1:
                continue
            sole = field_names[0]
            col = self._columns.get((name, sole))
            if col is not None and not col.pk:
                col.unique = True

        return table

    def _make_column(
        self, table_name: str, field_def: dict[str, Any], pk_names: set[str]
    ) -> Column | None:
        fname = field_def.get("Name")
        if not fname:
            return None

        type_def = field_def.get("TypeDefinition") or {}
        type_str = map_al_type(field_def)
        col_type: Any = type_str
        if str(type_def.get("Name") or "").lower() == "enum":
            subtype_name = (type_def.get("Subtype") or {}).get("Name")
            if subtype_name and subtype_name in self._enums:
                col_type = self._enums[subtype_name]

        is_pk = fname in pk_names
        field_props = properties.normalize(field_def.get("Properties"))
        # AL spells the non-nullable signal as 'NotBlank'; tolerate 'NotNull' too.
        # DBML PK already implies not-null, so don't double-mark PK columns.
        not_null = not is_pk and bool(field_props.get("NotBlank") or field_props.get("NotNull"))

        col = Column(name=fname, type=col_type, pk=is_pk, not_null=not_null)

        notes_parts: list[str] = []

        # aldoc description (when --docs supplies one) is the richest prose
        # available: it comes from the AL ToolTip property and /// XML doc
        # comments parsed by the real AL compiler. It takes priority over
        # Caption, which is then suppressed entirely as redundant.
        aldoc_description = self.docs.field_descriptions.get((table_name, fname))
        if aldoc_description:
            notes_parts.append(aldoc_description)

        caption = field_props.get("Caption")
        # Skip caption when it just restates the field name (~96% of Base
        # Application fields), and also when an aldoc description has already
        # claimed the leading slot. Otherwise the caption stays as a fallback
        # note when nothing richer is available.
        if not aldoc_description and caption and str(caption) != fname:
            notes_parts.append(str(caption))

        relation = field_props.get("TableRelation") or field_def.get("TableRelation")
        if relation:
            branches = relations.parse_conditional_relation(relation)
            if branches is not None:
                branch_parts: list[str] = []
                for if_cond, br_table, br_field, br_where in branches:
                    if br_table:
                        self._pending_refs.append(
                            _PendingRef(
                                source_table=table_name,
                                source_field=fname,
                                target_table=br_table,
                                target_field=br_field,
                                condition=br_where,
                                if_condition=if_cond,
                            )
                        )
                    label = (
                        f'{br_table}."{br_field}"' if (br_table and br_field) else (br_table or "?")
                    )
                    head = f"`IF {if_cond}`" if if_cond else "`ELSE`"
                    piece = f"{head} → `{label}`"
                    if br_where:
                        piece += f" where `{br_where}`"
                    branch_parts.append(piece)
                if branch_parts:
                    # HTML <br> renders as a visible line break in dbdiagram/
                    # dbdocs Markdown without triggering pydbml's multi-line
                    # indent bug; one branch per visual line is much more
                    # readable than the 6-branch one-liners on real BC fields.
                    bullets = "<br>".join(f"• {p}" for p in branch_parts)
                    notes_parts.append(f"**Conditional reference:**<br>{bullets}")
            else:
                target_table, target_field, condition = relations.parse_relation_string(relation)
                if target_table:
                    self._pending_refs.append(
                        _PendingRef(
                            source_table=table_name,
                            source_field=fname,
                            target_table=target_table,
                            target_field=target_field,
                            condition=condition,
                        )
                    )
                    if condition:
                        notes_parts.append(f"**Condition:** `{condition}`")

        if notes_parts:
            # Single physical line (avoids pydbml's textwrap.indent breaking
            # Markdown inside multi-line [note: '''...''']); '<br><br>' renders
            # as a paragraph-style gap in dbdiagram/dbdocs Markdown so sections
            # (caption / condition / references) look visually separated.
            col.note = Note("<br><br>".join(notes_parts))
        return col

    def _merge_table_extensions(self) -> None:
        for ext in self.symbols.get("TableExtensions") or []:
            target = ext.get("TargetObject") or ext.get("Target")
            if not target:
                continue
            table = self._tables.get(target)
            if table is None:
                table = Table(
                    name=target,
                    schema=self.table_schema,
                    note=f"Stub for cross-package target {target}",
                )
                self._tables[target] = table
                self.db.add(table)
            for f in ext.get("Fields") or []:
                col = self._make_column(target, f, set())
                if col is not None:
                    table.add_column(col)
                    self._columns[(target, col.name)] = col

    def _build_extension_stubs(self) -> None:
        for ext in self.symbols.get("TableExtensions") or []:
            target = ext.get("TargetObject") or ext.get("Target")
            if not target:
                continue
            stub_name = f"{target} (Extension)"
            stub = Table(name=stub_name, schema=self.table_schema, note=f"Extension of {target}")
            for f in ext.get("Fields") or []:
                col = self._make_column(stub_name, f, set())
                if col is not None:
                    stub.add_column(col)
                    self._columns[(stub_name, col.name)] = col
            self._tables[stub_name] = stub
            self.db.add(stub)

    def _resolve_references(self) -> None:
        # Real-world AL has fields with multiple TableRelation clauses that resolve to
        # the same (source_col, target_col) pair, and IF/ELSE branches occasionally
        # point two branches at the same target. pydbml rejects duplicate Refs, so we
        # dedupe by (source_col id, target_col id) before adding.
        seen: set[tuple[int, int]] = set()
        # Cross-package and missing-target notes are append-only; dedupe them per
        # source column so a 6-branch IF/ELSE all pointing at the same missing
        # target doesn't produce 6 identical 'References X (cross-package)' notes.
        noted_targets: dict[int, set[str]] = {}
        for ref in self._pending_refs:
            source_col = self._columns.get((ref.source_table, ref.source_field))
            if source_col is None:
                continue

            target_table = self._tables.get(ref.target_table)
            if target_table is None:
                target_label = (
                    f'`{ref.target_table}."{ref.target_field}"`'
                    if ref.target_field
                    else f"`{ref.target_table}`"
                )
                col_noted = noted_targets.setdefault(id(source_col), set())
                key_label = f"cross-package:{target_label}"
                if key_label not in col_noted:
                    self._append_note(source_col, f"**References** {target_label} (cross-package)")
                    col_noted.add(key_label)
                continue

            target_col = None
            if ref.target_field is not None:
                target_col = self._columns.get((ref.target_table, ref.target_field))
            if target_col is None:
                pk_cols = [c for c in target_table.columns if c.pk]
                if not pk_cols:
                    target_label = (
                        f'`{ref.target_table}."{ref.target_field}"`'
                        if ref.target_field
                        else f"`{ref.target_table}`"
                    )
                    col_noted = noted_targets.setdefault(id(source_col), set())
                    key_label = f"pkless:{target_label}"
                    if key_label not in col_noted:
                        self._append_note(source_col, f"**References** {target_label}")
                        col_noted.add(key_label)
                    continue
                target_col = pk_cols[0]

            if source_col is target_col:
                # Self-referential TableRelation (some BC tables declare a
                # field that references itself, e.g. 'refers to original').
                # Skip emitting a no-op Ref that just adds visual noise.
                continue
            key = (id(source_col), id(target_col))
            if key in seen:
                continue
            seen.add(key)

            # Carry the IF condition and any WHERE filter onto the Ref itself as
            # a pydbml comment, which renders as a '//' line above the Ref { }
            # block in DBML. The diagram thus shows *why* each arrow exists when
            # a column has multiple conditional branches resolving to different
            # targets. Non-conditional refs leave comment as None.
            comment_parts: list[str] = []
            if ref.if_condition:
                comment_parts.append(f"when {ref.if_condition}")
            if ref.condition:
                comment_parts.append(f"where {ref.condition}")
            comment = "; ".join(comment_parts) if comment_parts else None

            ref_obj = Reference(type=">", col1=source_col, col2=target_col, comment=comment)
            # pydbml.Database.add_reference performs an O(n) duplicate check via
            # Reference.__eq__ that recurses through both columns and both tables.
            # On Base Application (~8k refs) that ballooned build time to several
            # minutes. We already dedupe by (id(src), id(tgt)) above, so the
            # check is redundant; inline the cheap parts of add_reference here.
            ref_obj.database = self.db
            self.db.refs.append(ref_obj)

    def _apply_table_filters(self) -> None:
        """Drop tables that don't match the include/exclude glob patterns.

        ``includes`` is a positive filter: when non-empty, tables matching *none* of the
        include patterns are removed. ``excludes`` is a negative filter applied after:
        tables matching *any* exclude pattern are removed. Refs into a removed target
        degrade naturally to cross-package notes via the existing _resolve_references
        path, since the target table is gone from ``self._tables``.
        """
        from fnmatch import fnmatchcase

        def keep(name: str) -> bool:
            if self.includes and not any(fnmatchcase(name, p) for p in self.includes):
                return False
            if self.excludes and any(fnmatchcase(name, p) for p in self.excludes):
                return False
            return True

        dropped = {name for name in self._tables if not keep(name)}
        for name in dropped:
            table = self._tables.pop(name)
            self._table_namespaces.pop(name, None)
            # Remove column entries for this table so references can't accidentally
            # rebind to a column on a filtered-out table.
            for key in list(self._columns):
                if key[0] == name:
                    del self._columns[key]
            try:
                self.db.delete_table(table)
            except Exception:  # noqa: BLE001 — defensive against pydbml internal changes
                pass

    def _build_groups(self) -> None:
        for tg in build_table_groups(
            self._tables.values(), self.grouping, namespaces=self._table_namespaces
        ):
            self.db.add(tg)

    @staticmethod
    def _append_note(col: Column, line: str) -> None:
        existing = col.note.text if col.note else ""
        # '<br><br>' renders as a paragraph gap in dbdiagram/dbdocs Markdown;
        # plain '\n' breaks because pydbml's textwrap.indent prepends 4 spaces
        # to continuation lines, which Markdown then treats as a code block.
        col.note = Note(f"{existing}<br><br>{line}" if existing else line)

    # Thin shim kept for tests / external callers reaching the static name.
    _properties = staticmethod(properties.normalize)

    # Thin shims that defer to the al2dbml.relations module; kept on the
    # class so existing tests that reach Generator._parse_* continue to work
    # without churn. Internal call sites use relations.* directly.
    _parse_relation_string = staticmethod(relations.parse_relation_string)
    _parse_conditional_relation = staticmethod(relations.parse_conditional_relation)
    _parse_qualified = staticmethod(relations.parse_qualified)
    _find_matching_paren = staticmethod(relations.find_matching_paren)


def generate(app_path: str | Path, output_path: str | Path | None = None) -> str:
    """Convenience wrapper: load ``app_path``, render DBML, optionally write to ``output_path``."""
    gen = Generator.from_app(app_path)
    rendered = gen.dbml()
    if output_path is not None:
        Path(output_path).write_text(rendered, encoding="utf-8")
    return rendered
